language: node_js
node_js:
- 14.5.0
script: "./scripts/release"
if: tag IS present
deploy:
  provider: releases
  api_key:
    secure: "gU/HRPwj1pgzqxehM4JtrNvGKZiRjZbvBFeoL/RBeoAxBNuL4fxvG8GmASWyFCF94MveobrsAr6pz0o2jvEyXYOu3LxlN+Jecezrifwxus6rYy5XbXgaDLrnsWfB/EQgO8ST0/MxuMOMRXz58l6/QRnzgguK19Xb2iJpCXe6Ajsy1uGxgUTVZw1iDhacv2nyGwy0/EPWwPWoV+OlpYAXpmCxt/JO3AQ+OeVxQodYYPN0ZAQe0nvPBtoRtGRRJ2s5nbY8wMw862aOU5aLjo+miL2E9v9rt1sxect8XYfAEXZ8nd+wmWjeVqVAWWXbwITQtNzjRE6PY8RCus/k36nF0lsz8tD8lrGUtg6JddzY7LeJ+a0FGcmTrEO86w2kGM9bfl94WHbI+Z9cHIQso88OrzNZU1lZ9XLpK2rCOVgpjtzDkLhSRsvTJyUrSkrDkLTJis3zuK8aLRHuVz7E+F1BVJjFtvd2aIWilHBnci4CXGa2A4Q22VOyAlXZExJABxaF+b2Da7OlDNFr6pbu+GuYbnUyWj5gTL1OaQlTk2yiOOXpbcirEduAkpsTEDfDW30BgaLifT3ZcRnY7P3f1hUgfAVnsv0Nabkhmzc270LSpB88DUQrjSBg4NHmacsspZCZNRc8hEs+GrjPfn8O+t60vKAUYpMVQG7tegz/LxFHYHg="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/acms-ui
    tags: true    
