language: node_js
node_js:
  - '6'

script: npm run release

deploy:
  provider: releases
  api_key:
    secure: r29ctBeeojXJ+prIOajj6ObEh4a0Oel4aXpq2FFRbRjJVTkcRWUMgkPMwupftpzgncY5QMnNVjWCeYDq44+/HqUdODDDlq+9wTv++Vbrqn9caNmq0ADVcL0v3Da+9sTkrpdPuP602v/kzeaAoTcKGfBhB+Iu4xG3xWxcgzLo3/Dvkze7+QJYRnLjRO7gfb0lNzm96YXKFUPSXevzk9FO+va+Dcf6FIxaSz7RrrrdS9xeYqmx+T+DN1pc3iLMoaHHel6BaXMRLneUYNBiBfnPRpIDeR60FAGOIvaiUkUxDaglcS+HSQZoTdId4nXCFXZOuUnkGWvilNo1t8vfck0Htdu5cmA4XFJDg8uToTnelFGHcHEIiVzjSWfSTxsv3NCC+2uARSM3kvX7t28ZllrCsnqJFBM1yJdW9+1ZJUKBCnoZTk+EcqBwsKfyJVMDf+EGTsLTVa5cAG0e5gnSHhtAika1z2xuTItSJqoN9R20aB8aFZHAWYj/wXS5SGAeYe2zu0bnVMopvaKhSxewuyXaJ0SyJo3yat9xC24/FTd5h+N2UPNadixtbDnmLNRoVuHE+3BnTARdMU+HGR1SzOYl63nXwNzvsA8zQEffM26WdOVBEwQoJpkgr+hJjEl3dG2bqKvQuDBbuGES5b8FyHeumq4GjY/EykvmrfxZfpbtRhc=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: artcom/git-json-cms
    tags: true
