language: node_js
node_js:
  - '14.5.0'

script: ./scripts/release

deploy:
  provider: releases
  api_key:
    secure: "CXgyw52ZIy+bxOrtUcw8XAIsf5ysCLnYcg+p/+n41hG9hxlF7kE38OSh7peBzYRFzutdnyR/URg3Fk04eD0NHRObA6nV1rWMTPnHTiVBjfBrGVrLo6bBGqNJPr9JekNPAOiJrI3GtttC5UENtvnT0DKJ69IaQOsMUOF1DVQ7MwVNxVqoY/45o0SUKLiStZiYIOJ7CW8kD0DLgSztN6NAwM4YfYMjVNB9xN4OInZ4sT1e4InIpVedCvzIhmXFOG36IVRVsKnn95LUOYR56exI7Pc57NcqqXAugLTt/JMoq091XoMtkPPpu48DZ5AmLNgPiV4TI4XBZvBqKR7pHlzOndvZ9whJZ0wPVEajO8m2rVojUL0KY9akFhOp8yGjMNCRaqg46YL1yN07MaSkQASWsE+nY+pkfUx0qeVdgsNzuj8b7z+MiVZ1d025B+ikS8YfMNjaxBNOBztiIcUJzJVnzlDIJcsOBS40Pzl7IWA6GXoiLuG9vyIBw692TwFiytdSY19UpvY/UgNP4MHyrihzIoNGMYwN6EPLyov9WS/FVTQOIOEHPMPEWZX0ofb5n8VtLdFMr8Bzk0JsnZaMAkog0JfUpwsHlwrtruDbOSrck7/Ifn4Oo0BXGb2udNed/E+CZSPKefUQKqSrh7gNIlrasxI5X+Oz2+QT8Gj0R1n8ze8="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/acms-ui
    tags: true
