FROM node:latest

# set working directory
RUN mkdir /app
WORKDIR /app

# install and cache app dependencies
ADD package.json /app/package.json
ADD package-lock.json /app/package-lock.json
RUN npm install

ADD webpack.config.js /app/webpack.config.js
ADD .babelrc /app/.babelrc
ADD src /app/src

RUN npm run build

ADD public/index.html /app/public/index.html

# start app
CMD ["npm", "start"]
