#!/bin/bash

set -eo pipefail

DIST_DIR="dist"
BUILD_DIR="build"

echo "Cleaning up"
rm -rf "${DIST_DIR}"

echo "Building"
npm run build

echo "Packaging"
cd "${DIST_DIR}"
zip -r -9 "../${BUILD_DIR}/git-json-cms-${TRAVIS_TAG:-master}.zip" *
tar czvf "../${BUILD_DIR}/git-json-cms-${TRAVIS_TAG:-master}.tar.gz" *
