#!/bin/bash

set -eo pipefail

DIST_DIR="dist"

echo "Cleaning up"
rm -rf "${DIST_DIR}"

echo "Building"
npm run build

echo "Packaging"
cd "${DIST_DIR}"
mkdir artifacts
zip -r -9 "./artifacts/git-json-cms-${TRAVIS_TAG:-master}.zip" *
tar czvf "./artifacts/git-json-cms-${TRAVIS_TAG:-master}.tar.gz" *
